--
-- PostgreSQL database dump
--

\restrict Y9j4m36l6SEh9LdRvPPR8W9HalofK9uo8pO04ifPVcTDVXN4lzqzVguitbmfen7

-- Dumped from database version 17.10 (Ubuntu 17.10-1.pgdg24.04+1)
-- Dumped by pg_dump version 17.10 (Ubuntu 17.10-1.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: plik_metadane; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.plik_metadane (
    id bigint NOT NULL,
    data_przeslania timestamp(6) without time zone NOT NULL,
    nazwa_pliku character varying(255) NOT NULL,
    rozmiar bigint,
    sciezka_pliku character varying(255) NOT NULL,
    typ_pliku character varying(255),
    projekt_id bigint,
    przeslany_przez_id bigint,
    zadanie_id bigint
);


ALTER TABLE public.plik_metadane OWNER TO postgres;

--
-- Name: plik_metadane_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.plik_metadane ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plik_metadane_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: projekt; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.projekt (
    id bigint NOT NULL,
    data_oddania date NOT NULL,
    nazwa character varying(255) NOT NULL,
    opis text,
    utworzony timestamp(6) without time zone NOT NULL,
    zmodyfikowany timestamp(6) without time zone NOT NULL
);


ALTER TABLE public.projekt OWNER TO postgres;

--
-- Name: projekt_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.projekt ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projekt_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: projekt_student; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.projekt_student (
    projekt_id bigint NOT NULL,
    student_id bigint NOT NULL
);


ALTER TABLE public.projekt_student OWNER TO postgres;

--
-- Name: refresh_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.refresh_token (
    id bigint NOT NULL,
    data_wygasniecia timestamp(6) with time zone NOT NULL,
    token character varying(255) NOT NULL,
    uzytkownik_id bigint
);


ALTER TABLE public.refresh_token OWNER TO postgres;

--
-- Name: refresh_token_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.refresh_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: uzytkownik; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.uzytkownik (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    forma_studiow character varying(255),
    imie character varying(255) NOT NULL,
    nazwisko character varying(255) NOT NULL,
    nr_indeksu character varying(255),
    password_hash character varying(255) NOT NULL,
    rola character varying(255) NOT NULL,
    CONSTRAINT uzytkownik_rola_check CHECK (((rola)::text = ANY ((ARRAY['ROLE_STUDENT'::character varying, 'ROLE_PROWADZACY'::character varying])::text[])))
);


ALTER TABLE public.uzytkownik OWNER TO postgres;

--
-- Name: uzytkownik_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.uzytkownik ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.uzytkownik_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wiadomosc_chat; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wiadomosc_chat (
    id bigint NOT NULL,
    data_wyslania timestamp(6) without time zone NOT NULL,
    tresc character varying(1000) NOT NULL,
    nadawca_id bigint NOT NULL,
    projekt_id bigint
);


ALTER TABLE public.wiadomosc_chat OWNER TO postgres;

--
-- Name: wiadomosc_chat_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wiadomosc_chat ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wiadomosc_chat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: zadanie; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.zadanie (
    id bigint NOT NULL,
    data_utworzenia timestamp(6) without time zone NOT NULL,
    kolejnosc integer,
    nazwa character varying(255) NOT NULL,
    opis text,
    status character varying(255) NOT NULL,
    projekt_id bigint NOT NULL,
    przypisany_student_id bigint,
    CONSTRAINT zadanie_status_check CHECK (((status)::text = ANY ((ARRAY['TODO'::character varying, 'IN_PROGRESS'::character varying, 'DONE'::character varying])::text[])))
);


ALTER TABLE public.zadanie OWNER TO postgres;

--
-- Name: zadanie_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.zadanie ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.zadanie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plik_metadane plik_metadane_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plik_metadane
    ADD CONSTRAINT plik_metadane_pkey PRIMARY KEY (id);


--
-- Name: projekt projekt_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.projekt
    ADD CONSTRAINT projekt_pkey PRIMARY KEY (id);


--
-- Name: projekt_student projekt_student_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.projekt_student
    ADD CONSTRAINT projekt_student_pkey PRIMARY KEY (projekt_id, student_id);


--
-- Name: refresh_token refresh_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (id);


--
-- Name: uzytkownik uk7tt9rs0qneii2pkjjdxubfe2d; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.uzytkownik
    ADD CONSTRAINT uk7tt9rs0qneii2pkjjdxubfe2d UNIQUE (email);


--
-- Name: refresh_token ukg230i8w8wmh4lgmgb0wott2ww; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT ukg230i8w8wmh4lgmgb0wott2ww UNIQUE (uzytkownik_id);


--
-- Name: refresh_token ukr4k4edos30bx9neoq81mdvwph; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT ukr4k4edos30bx9neoq81mdvwph UNIQUE (token);


--
-- Name: uzytkownik uzytkownik_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.uzytkownik
    ADD CONSTRAINT uzytkownik_pkey PRIMARY KEY (id);


--
-- Name: wiadomosc_chat wiadomosc_chat_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wiadomosc_chat
    ADD CONSTRAINT wiadomosc_chat_pkey PRIMARY KEY (id);


--
-- Name: zadanie zadanie_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zadanie
    ADD CONSTRAINT zadanie_pkey PRIMARY KEY (id);


--
-- Name: projekt_student fk4yeyuijvuxocjp69ogsgir1sc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.projekt_student
    ADD CONSTRAINT fk4yeyuijvuxocjp69ogsgir1sc FOREIGN KEY (student_id) REFERENCES public.uzytkownik(id);


--
-- Name: wiadomosc_chat fk52x2luv89ix1xwyvquutuwng6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wiadomosc_chat
    ADD CONSTRAINT fk52x2luv89ix1xwyvquutuwng6 FOREIGN KEY (projekt_id) REFERENCES public.projekt(id);


--
-- Name: zadanie fkaupfb9wjo0o9fu7bm2s5tifid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zadanie
    ADD CONSTRAINT fkaupfb9wjo0o9fu7bm2s5tifid FOREIGN KEY (projekt_id) REFERENCES public.projekt(id);


--
-- Name: zadanie fkc0cv1hfdtuh7rngxbifv2b1ig; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zadanie
    ADD CONSTRAINT fkc0cv1hfdtuh7rngxbifv2b1ig FOREIGN KEY (przypisany_student_id) REFERENCES public.uzytkownik(id);


--
-- Name: projekt_student fkewgsag67wtfolcpc3vbjf96ky; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.projekt_student
    ADD CONSTRAINT fkewgsag67wtfolcpc3vbjf96ky FOREIGN KEY (projekt_id) REFERENCES public.projekt(id);


--
-- Name: plik_metadane fkj2tsqfnmkpyb5iuon42s8jv87; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plik_metadane
    ADD CONSTRAINT fkj2tsqfnmkpyb5iuon42s8jv87 FOREIGN KEY (zadanie_id) REFERENCES public.zadanie(id);


--
-- Name: wiadomosc_chat fkohbeqfow6p3s35mnevti78dui; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wiadomosc_chat
    ADD CONSTRAINT fkohbeqfow6p3s35mnevti78dui FOREIGN KEY (nadawca_id) REFERENCES public.uzytkownik(id);


--
-- Name: plik_metadane fkq365pcxcdojk2cxsq5r9y1qx6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plik_metadane
    ADD CONSTRAINT fkq365pcxcdojk2cxsq5r9y1qx6 FOREIGN KEY (przeslany_przez_id) REFERENCES public.uzytkownik(id);


--
-- Name: plik_metadane fkt5tx28dfvkcd9ksmqqnygelmu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plik_metadane
    ADD CONSTRAINT fkt5tx28dfvkcd9ksmqqnygelmu FOREIGN KEY (projekt_id) REFERENCES public.projekt(id);


--
-- Name: refresh_token fktg0sce1k9gnmb5i5r0nangvf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT fktg0sce1k9gnmb5i5r0nangvf FOREIGN KEY (uzytkownik_id) REFERENCES public.uzytkownik(id);


--
-- PostgreSQL database dump complete
--

\unrestrict Y9j4m36l6SEh9LdRvPPR8W9HalofK9uo8pO04ifPVcTDVXN4lzqzVguitbmfen7

